# ./scripts/** testing using jest

name: Run tests for Sripts

on:
  push:
    branches: master
    paths: 'scripts/**'

  pull_request:
    paths: 'scripts/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  scripts-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check package-lock version
        uses: asyncapi/.github/.github/actions/get-node-version-from-package-lock@master
        id: lockversion

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.lockversion.outputs.version }}"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run Script Tests
        run: npm run test:jest
